version: '3'

services:
  db:
    image: mysql:8
    container_name: parking-db
    command: --innodb_use_native_aio=0
    restart: always
    tty: true
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - default

networks:
  default:
    driver: bridge
